package mleith785.cs499.firebasedb;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;


import java.util.ArrayList;
import java.util.List;


//!!!! imported to try running database
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.Query;
import com.google.firebase.database.ValueEventListener;

import static android.content.ContentValues.TAG;


public class Campsite_DB_Test extends AppCompatActivity
{



    private TextView CampsiteIdGui;
    private EditText CampsiteNameGui;
    private EditText CampsiteCityGui;
    private EditText CampsiteLocationGui;
    private EditText CampsiteAvgRatingGui;
    private CheckBox RiversideCBGui;
    private CheckBox GrillCBGui;
    private CheckBox RestroomsCBGui;
    private EditText CampsiteDetailsGui;



    private Spinner RatingDropdown;
    private String[] items;
    private List<String> CampsiteStrIds;
    private int CampsiteIndex;


    //ALL THE CHANGES HAPPEN HERE FOR CS499
    private static final boolean DEBUG_UPDATE = false;
    private Campsite CurrentCampsite;

    private List<Campsite> CampsiteList;
    private FirebaseDatabase database;
    private DatabaseReference myRef;

    /**
     * <h1> Create this activity and grab hold of the widgets.</h1>
     * Populate the spinner with some values
     * @param savedInstanceState
     */
    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_campsite_db_test);
        /* Stolen from
           https://stackoverflow.com/questions/13377361/how-to-create-a-drop-down-list
         */
        RatingDropdown = findViewById(R.id.spinnerRating);
        items = new String[]{"1", "2", "3", "4", "5"};
        ArrayAdapter<String> adapter = new ArrayAdapter<>(this,
                android.R.layout.simple_spinner_dropdown_item, items);
        RatingDropdown.setAdapter(adapter);

        //Grab the remaining widgets
        CampsiteIdGui = findViewById(R.id.CampsiteIdGui);
        CampsiteNameGui = findViewById(R.id.CampsiteNameGui);
        CampsiteCityGui = findViewById(R.id.CampsiteCityGui);
        CampsiteLocationGui = findViewById(R.id.CampsiteLocationGui);
        CampsiteAvgRatingGui = findViewById(R.id.CampsiteAvgRatingGui);
        RiversideCBGui = findViewById(R.id.RiversideCB);
        GrillCBGui = findViewById(R.id.GrillCB);
        RestroomsCBGui = findViewById(R.id.RestroomsCB);
        CampsiteDetailsGui = findViewById(R.id.CampsiteDetailsGui);

        if(DEBUG_UPDATE)
            UpdateCampsiteIds();

        CampsiteList = new ArrayList<Campsite>();
        CampsiteStrIds = new ArrayList<String>();

        UpdateCampsiteIds();

    }

    ValueEventListener GetNumCampsites = new ValueEventListener()        {
        @Override
        public void onDataChange(DataSnapshot dataSnapshot)
        {
            if (dataSnapshot.exists()){
                //Need to clear out the campsite IDs of the existing list to keep this in sync
                CampsiteStrIds.clear();
                for(DataSnapshot snapshot: dataSnapshot.getChildren()){
                    //This gets the child node key = the one auto generated by firebase
                    CampsiteStrIds.add(snapshot.getKey());
                }
            }
//                Log.d(TAG, "Value is: " + value);

        }

        @Override
        public void onCancelled(DatabaseError error)
        {
            // Failed to read value
            Log.w(TAG, "Failed to read value.", error.toException());
        }
    };

    ValueEventListener valueEventListener = new ValueEventListener()        {
        @Override
        public void onDataChange(DataSnapshot dataSnapshot)
        {
                if (dataSnapshot.exists()){

                    Campsite single_site = dataSnapshot.getValue(Campsite.class);
                    CurrentCampsite = single_site;
                    String site_key = dataSnapshot.getKey();
                    PopulateSearchResults(single_site, site_key);
                }
//                Log.d(TAG, "Value is: " + value);

        }

        @Override
        public void onCancelled(DatabaseError error)
        {
            // Failed to read value
            Log.w(TAG, "Failed to read value.", error.toException());
        }
    };

    public void UpdateRecBtn(View view)
    {
        //Grab the data from the form for updating:


        CurrentCampsite.CampName = CampsiteNameGui.getText().toString();
        CurrentCampsite.CampCity = CampsiteCityGui.getText().toString();
        CurrentCampsite.CampLoc = CampsiteLocationGui.getText().toString();
        //CurrentCampsite.AvgRating = CampsiteAvgRatingGui.value;
        CurrentCampsite.FeatRiverside =  RiversideCBGui.isChecked();
        CurrentCampsite.FeatGrill = GrillCBGui.isChecked();
        CurrentCampsite.FeatRestroom = RestroomsCBGui.isChecked();
        CurrentCampsite.Details = CampsiteDetailsGui.getText().toString();

        String campsite_key = CampsiteStrIds.get(CampsiteIndex);
        FirebaseDatabase.getInstance().getReference().child("Campsites").child(campsite_key).setValue(CurrentCampsite);


    }

    public void SearchByName(View view)
    {

        String camp_name = CampsiteNameGui.getText().toString();
        Query query = FirebaseDatabase.getInstance().getReference("Campsites")
                .orderByChild("CampName")
                .equalTo(camp_name)
                .limitToFirst(1);

        query.addListenerForSingleValueEvent(new ValueEventListener(){
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                if ( dataSnapshot.exists())
                {
                    for(DataSnapshot snapshot: dataSnapshot.getChildren())
                    {
                        Campsite single_site = snapshot.getValue(Campsite.class);
                        String campsite_key = snapshot.getKey();
                        PopulateSearchResults(single_site, campsite_key);
                    }
                   // Campsite found_by_name = dataSnapshot.getValue(Campsite.class);
                   // PopulateSearchResults(found_by_name);
                }
            }

            @Override
            public void onCancelled(DatabaseError databaseError) {
                Log.e(TAG, "onCancelled", databaseError.toException());
            }
        });
    }

    public void CampDetailsBtn(View view)
    {
        Intent intent = new Intent(this, Image_test.class);
        startActivity(intent);

    }

    public void BtnPrevGui(View view)
    {

        String campsite_id_text = CampsiteIdGui.getText().toString();
        if (0 != campsite_id_text.compareTo("Auto Assigned"))
        {
            if (CampsiteIndex != 0)
            {
                CampsiteIndex--;
            }
        }
        else
        {
            CampsiteIndex=CampsiteStrIds.size()-1;
        }

//This works
//        Query query = FirebaseDatabase.getInstance().getReference("Campsites")
//                .orderByChild("CampCity").equalTo("Prior Lake");

//        Query query = FirebaseDatabase.getInstance().getReference("Campsites")
//                .orderByChild("CampId").equalTo(CampsiteIds.get(CampsiteIndex));

        Query query = FirebaseDatabase.getInstance().getReference("Campsites").child(CampsiteStrIds.get(CampsiteIndex));


        query.addListenerForSingleValueEvent(valueEventListener);

    }

    public void BtnNextGui(View view)
    {

        String campsite_id_text = CampsiteIdGui.getText().toString();
        if (0 != campsite_id_text.compareTo("Auto Assigned"))
        {
            if (CampsiteIndex < CampsiteStrIds.size() - 1)
            {
                CampsiteIndex++;
            }
        }
        else
        {
            CampsiteIndex = 0;
        }

        // Old way with using campsite ID
//        int campsite_id = CampsiteIds.get(CampsiteIndex);
//        Query query = FirebaseDatabase.getInstance().getReference("Campsites")
//                .orderByChild("CampId").equalTo(CampsiteIds.get(CampsiteIndex));

        Query query = FirebaseDatabase.getInstance().getReference("Campsites").child(CampsiteStrIds.get(CampsiteIndex));

        query.addListenerForSingleValueEvent(valueEventListener);
        //SearchCampsiteById(campsite_id);
    }





    private void PopulateSearchResults(Campsite campsite, String campsite_key)
    {
        if (null != campsite)
        {
            CampsiteIdGui.setText(campsite_key);
            CampsiteNameGui.setText(campsite.CampName);
            CampsiteCityGui.setText(campsite.CampCity);
            CampsiteLocationGui.setText(campsite.CampLoc);
            CampsiteAvgRatingGui.setText(String.valueOf(campsite.AvgRating));
            RiversideCBGui.setChecked(campsite.FeatRiverside);
            GrillCBGui.setChecked(campsite.FeatGrill);
            RestroomsCBGui.setChecked(campsite.FeatRestroom);
            RatingDropdown.setSelection(2); //test to see if this comes out as 1
            CampsiteDetailsGui.setText(campsite.Details);

        }
        else
        {
            //Blank out values
            CampsiteIdGui.setText("Auto Assigned");
            CampsiteNameGui.setText("");
            CampsiteCityGui.setText("");
            CampsiteLocationGui.setText("");
            CampsiteAvgRatingGui.setText("");
            RiversideCBGui.setChecked(false);
            GrillCBGui.setChecked(false);
            RestroomsCBGui.setChecked(false);
            RatingDropdown.setSelection(4);//test to see if this comes out as 3
            CampsiteDetailsGui.setText("");
        }

    }

    public void AddRecord(View view)
    {
        Campsite new_site = new Campsite(
                CampsiteNameGui.getText().toString(),
                CampsiteCityGui.getText().toString(),
                CampsiteLocationGui.getText().toString(),
                (float) 0.0,
                RiversideCBGui.isChecked(),
                GrillCBGui.isChecked(),
                RestroomsCBGui.isChecked(),
                CampsiteDetailsGui.getText().toString(),
                3.0f,4.0f
                );

        //Firebase get a key for the data
        //get the key for the campsite
        myRef = database.getReference("Campsites");
        String new_add_id = myRef.push().getKey();
        //Now write to the database
        myRef.child(new_add_id).setValue(new_site);
        Toast.makeText(this, "campsite added", Toast.LENGTH_LONG).show();
        UpdateCampsiteIds();

    }

    public void DeleteRecord(View view)
    {

        Query query = FirebaseDatabase.getInstance().getReference("Campsites").child(CampsiteStrIds.get(CampsiteIndex));

        query.addListenerForSingleValueEvent(new ValueEventListener(){
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                dataSnapshot.getRef().removeValue();
                UpdateCampsiteIds();

            }

            @Override
            public void onCancelled(DatabaseError databaseError) {
                Log.e(TAG, "onCancelled", databaseError.toException());
            }
        });


    }

    private void UpdateCampsiteIds()
    {
        database = FirebaseDatabase.getInstance();
        myRef = database.getReference("Campsites");
        Query query = FirebaseDatabase.getInstance().getReference("Campsites");

        myRef.addValueEventListener(GetNumCampsites);
        PopulateSearchResults(null,null);
    }

}
